"""add raw_sivep_gripe

Revision ID: 0cafb56065db
Revises: 76da0e0af2ff
Create Date: 2026-02-23 15:49:27.929085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cafb56065db'
down_revision: Union[str, Sequence[str], None] = '76da0e0af2ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_sivep_gripe',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('ref_date', sa.Date(), nullable=False),
    sa.Column('geo_basis', sa.String(length=20), nullable=False),
    sa.Column('municipio_ibge', sa.String(length=50), nullable=False),
    sa.Column('disease', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('geo_basis', 'hash', name='uq_raw_sivep_gripe_hash')
    )
    op.create_index('ix_raw_sivep_gripe_q1', 'raw_sivep_gripe', ['geo_basis', 'municipio_ibge', 'ref_date'], unique=False)
    op.create_index('ix_raw_sivep_gripe_q2', 'raw_sivep_gripe', ['year', 'ref_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_sivep_gripe_q2', table_name='raw_sivep_gripe')
    op.drop_index('ix_raw_sivep_gripe_q1', table_name='raw_sivep_gripe')
    op.drop_table('raw_sivep_gripe')
    # ### end Alembic commands ###
