"""init

Revision ID: 76da0e0af2ff
Revises: 
Create Date: 2026-02-13 11:38:46.265678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76da0e0af2ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_dedup',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=200), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_table('bulletins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_code', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('url', sa.String(length=800), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code', 'external_id', name='uq_bulletin_source_external')
    )
    op.create_table('cases_weekly',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_code', sa.String(length=50), nullable=False),
    sa.Column('disease', sa.String(length=50), nullable=False),
    sa.Column('geo_level', sa.String(length=20), nullable=False),
    sa.Column('geo_code', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('epiweek', sa.Integer(), nullable=False),
    sa.Column('cases', sa.Integer(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code', 'disease', 'geo_code', 'year', 'epiweek', name='uq_cases_weekly')
    )
    op.create_table('epi_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_code', sa.String(length=50), nullable=False),
    sa.Column('disease', sa.String(length=50), nullable=False),
    sa.Column('geo_level', sa.String(length=20), nullable=False),
    sa.Column('geo_code', sa.String(length=50), nullable=False),
    sa.Column('geo_name', sa.String(length=200), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('epiweek', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code', 'disease', 'geo_code', 'year', 'epiweek', 'title', name='uq_epi_alert_identity')
    )
    op.create_table('indicators_weekly',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_code', sa.String(length=50), nullable=False),
    sa.Column('disease', sa.String(length=50), nullable=False),
    sa.Column('geo_level', sa.String(length=20), nullable=False),
    sa.Column('geo_code', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('epiweek', sa.Integer(), nullable=False),
    sa.Column('incidence', sa.Float(), nullable=True),
    sa.Column('rt', sa.Float(), nullable=True),
    sa.Column('alert_level', sa.Integer(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code', 'disease', 'geo_code', 'year', 'epiweek', name='uq_indicators_weekly')
    )
    op.create_table('ingestion_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_code', sa.String(length=50), nullable=False),
    sa.Column('geo_code', sa.String(length=50), nullable=False),
    sa.Column('disease', sa.String(length=50), nullable=False),
    sa.Column('ey_start', sa.Integer(), nullable=False),
    sa.Column('ey_end', sa.Integer(), nullable=False),
    sa.Column('ew_start', sa.Integer(), nullable=False),
    sa.Column('ew_end', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code', 'geo_code', 'disease', name='uq_target_source_geo_disease')
    )
    op.create_table('notification_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_url', sa.String(length=800), nullable=False),
    sa.Column('min_severity', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('disease_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geo_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources')
    op.drop_table('notification_targets')
    op.drop_table('ingestion_targets')
    op.drop_table('indicators_weekly')
    op.drop_table('epi_alerts')
    op.drop_table('cases_weekly')
    op.drop_table('bulletins')
    op.drop_table('alert_dedup')
    # ### end Alembic commands ###
